# Generated by Django 6.0.5 on 2026-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
