# Generated by Django 6.0.5 on 2026-06-06 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_appointment_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
